version: 2
updates:
  - package-ecosystem: npm
    directory: /gosso-admin-frontend
    schedule:
      interval: weekly
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /seed
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /gosso-admin-frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /seed
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
