server {
    listen 8080;
    server_name localhost;

    # OIDC Discovery, JWKS, and OAuth2
    location ~ ^/(\.well-known|oauth2|oidc) {
        proxy_pass http://gosso:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # GOSSO APIs
    location /api/v1/ {
        proxy_pass http://gosso:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # System readiness used by the admin dashboard
    location = /readiness {
        proxy_pass http://gosso:8080/readiness;
        add_header Cache-Control "no-store" always;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Swagger UI & OpenAPI Spec (exposing GOSSO's API Swagger)
    location /swagger {
        proxy_pass http://gosso:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React Admin Frontend static files & SPA routing
    location / {
        proxy_pass http://gosso-admin-frontend:8083;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
